application: lunchcost 
version: 7
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /static/bg\.jpg
  static_files: static/bg.jpg
  upload: static/bg\.jpg

- url: .*
  script: lunchcost.py
